-- MySQL Script generated by MySQL Workbench
-- Tue Dec 12 19:12:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema food_park
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema food_park
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `food_park` DEFAULT CHARACTER SET utf8 ;
USE `food_park` ;

-- -----------------------------------------------------
-- Table `food_park`.`truck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_park`.`truck` (
  `cnpj` VARCHAR(30) NOT NULL,
  `nome` VARCHAR(50) NULL,
  `razao_social` VARCHAR(50) NULL,
  `seguimento` VARCHAR(100) NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_park`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_park`.`responsavel` (
  `cpf` VARCHAR(30) NOT NULL,
  `nome` VARCHAR(50) NULL,
  `food_park_cnpj` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`cpf`, `food_park_cnpj`),
  INDEX `fk_responsavel_food_park1_idx` (`food_park_cnpj` ASC),
  CONSTRAINT `fk_responsavel_food_park1`
    FOREIGN KEY (`food_park_cnpj`)
    REFERENCES `food_park`.`truck` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_park`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_park`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `detalhe` TEXT(300) NULL,
  `preco` FLOAT(10,2) NULL,
  `food_park_cnpj` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idproduto`, `food_park_cnpj`),
  INDEX `fk_produto_food_park1_idx` (`food_park_cnpj` ASC),
  CONSTRAINT `fk_produto_food_park1`
    FOREIGN KEY (`food_park_cnpj`)
    REFERENCES `food_park`.`truck` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_park`.`promocao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_park`.`promocao` (
  `idpromocao` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  `descricao` TEXT(300) NULL,
  `status` CHAR(2) NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`idpromocao`, `produto_idproduto`),
  INDEX `fk_promocao_produto1_idx` (`produto_idproduto` ASC),
  CONSTRAINT `fk_promocao_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `food_park`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_park`.`contato_Truck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_park`.`contato_Truck` (
  `idcontato` INT NOT NULL AUTO_INCREMENT,
  `contato` TEXT(120) NULL,
  `rede_social` TEXT(120) NULL,
  `email` TEXT(100) NULL,
  `food_park_cnpj` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idcontato`, `food_park_cnpj`),
  INDEX `fk_contato_food_park1_idx` (`food_park_cnpj` ASC),
  CONSTRAINT `fk_contato_food_park1`
    FOREIGN KEY (`food_park_cnpj`)
    REFERENCES `food_park`.`truck` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `food_park`.`contato_Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `food_park`.`contato_Responsavel` (
  `idcontato` INT NOT NULL AUTO_INCREMENT,
  `contato` TEXT(120) NULL,
  `rede_social` TEXT(120) NULL,
  `email` TEXT(100) NULL,
  `responsavel_cpf` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idcontato`, `responsavel_cpf`),
  INDEX `fk_contato_copy1_responsavel1_idx` (`responsavel_cpf` ASC),
  CONSTRAINT `fk_contato_copy1_responsavel1`
    FOREIGN KEY (`responsavel_cpf`)
    REFERENCES `food_park`.`responsavel` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
